# Generated by Django 3.1.1 on 2020-09-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя артиста')),
                ('second_name', models.CharField(max_length=100, verbose_name='Фамилия артиста')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('dob', models.PositiveIntegerField(default=2020, verbose_name='Дата рождения')),
                ('photo', models.ImageField(upload_to='artists/', verbose_name='Фото')),
                ('slug', models.SlugField(max_length=201, unique=True)),
            ],
            options={
                'verbose_name': 'Артист',
                'verbose_name_plural': 'Артисты',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название жанра')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('artists', models.ManyToManyField(related_name='Artist', to='audiolib.Artist', verbose_name='Артист')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название группы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='band/', verbose_name='Логотип группы')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('artist', models.ManyToManyField(related_name='band_artists', to='audiolib.Artist', verbose_name='Артисты')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='band',
            field=models.ManyToManyField(blank=True, related_name='Band', to='audiolib.Band', verbose_name='Группа'),
        ),
    ]
