# Generated by Django 3.1.1 on 2020-09-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiolib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Псевдоним'),
        ),
        migrations.AddField(
            model_name='artist',
            name='surname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия артиста'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя артиста'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество\\Второе имя'),
        ),
    ]
