# Generated by Django 3.1.1 on 2020-09-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiolib', '0005_remove_userprofile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='bands',
            field=models.ManyToManyField(blank=True, to='audiolib.Band', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='band',
            name='artist',
            field=models.ManyToManyField(blank=True, related_name='band_artists', to='audiolib.Artist', verbose_name='Артисты'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='Artists', to='audiolib.Artist', verbose_name='Артисты'),
        ),
    ]
