# Generated by Django 3.1.1 on 2021-01-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiolib', '0006_auto_20200912_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
